sudo: false
language: scala
dist: xenial

matrix:
  include:
    - jdk: openjdk11
      script: sbt test
    - jdk: openjdk8
      script: sbt "+compile" "+test"
    - scala: scripted-test
      jdk: openjdk8
      env: SCRIPT=";+ publishLocal;+ sbt-plugin/scripted"
      script:
      - sbt "${SCRIPT}"
    - os: windows
      language: bash
      env: JDK="adopt@1.8.0-272"
      before_script:
      - wget https://raw.githubusercontent.com/DanySK/Gravis-CI/c8f400623d8f756ef7c/.install-jdk-travis.sh
      - source .install-jdk-travis.sh
      - wget https://raw.githubusercontent.com/paulp/sbt-extras/4d558c88ae6ae240e7a5eedc0cf33cc9e7bd0e58/sbt && chmod +x ./sbt
      script:
      - ./sbt test "+ publishLocal" "+ sbt-plugin/scripted"
cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/launchers"
    - "$HOME/.cache/coursier/v1"
before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
