sudo: false
language: scala
dist: xenial
scala:
  - 2.11.12
  - 2.12.8
  - 2.13.0
jdk:
  - openjdk8
matrix:
  include:
    - scala: 2.12.8
      jdk: openjdk11
    - scala: scripted-test
      jdk: openjdk8
      env: SCRIPT=";+ core/publishLocal;+ sbt-plugin/scripted"
      script:
      - sbt "${SCRIPT}"
script: sbt "++${TRAVIS_SCALA_VERSION} -v" compile test
cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/launchers"
before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
